# Default values for camunda-bpm-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageRegistry:
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass:

general:
  debug: false
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""

image:
  repository: camunda/camunda-bpm-platform
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

database:
  # In case H2 database is used.
  internal:
    enabled: true
    diskSize: 1G
  # In case PostgreSQL or MySQL databases are used.
  external:
    enabled: false
    credentialsSecretName: camunda-bpm-platform-credentials
    driver: org.postgresql.Driver
    url: jdbc:postgresql://camunda-bpm-postgresql:5432/postgres

# parameters will be also used by subchart @bitnami/postgresql
postgresql:
  postgresqlUsername: camunda-user
  postgresqlPassword: camunda
  postgresqlDatabase: camunda
  postgresqlPort: 5432

  # define if you create a PVC for the PostgreSQL database
  persistence:
    enabled: false

# parameters will be also used by subchart @bitnami/mysql
mysql:
  auth:
    username: camunda-user
    password: camunda
    database: camunda
    # you should alter this parameter on bootstrap
    rootPassword: mysql
  port: 3306

  # define if you create a PVC for the MySQL database
  primary:
    persistence:
      enabled: false

tags:
  managed-postgresql: false
  managed-mysql: false

service:
  type: ClusterIP
  port: 8080
  portName: http

metrics:
  enabled: false
  service:
    type: ClusterIP
    port: 9404
    portName: metrics
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/"
      prometheus.io/port: "9404"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: camunda-bpm-platform.local
      paths: []
  tls: []
  #  - secretName: camunda-bpm-platform-tls
  #    hosts:
  #      - camunda-bpm-platform.local

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
